[tool.mypy]
namespace_packages = true
explicit_package_bases = true

no_implicit_optional = true
strict_equality = true
implicit_reexport = false

warn_unused_configs = true
warn_unused_ignores = true
warn_return_any = true
warn_redundant_casts = true
warn_unreachable = true
check_untyped_defs = true

pretty = true
show_column_numbers = true
show_error_context = true
show_error_codes = true
show_traceback = true

[[tool.mypy.overrides]]
module = [
    "sympy",
]
ignore_missing_imports = true